# Файл представлений — визуализация плана
# Представления определяют, как отображать план, но НЕ влияют на расчёт расписания.
# В v2 excludes перенесён в schedule.calendars, здесь его нет.

version: 2

views:
  # ============================================================
  # Обзорное представление для руководства
  # ============================================================
  overview:
    title: "Обзор проекта"
    where:
      kind: [phase, epic]  # только фазы и эпики
      has_schedule: true   # только запланированные узлы
    order_by: start

  # ============================================================
  # Детальный Gantt для команды
  # ============================================================
  gantt-full:
    title: "Полная диаграмма Ганта"
    where:
      has_schedule: true
    
    lanes:
      backend:
        title: "Бэкенд"
        nodes: [api-auth, api-tasks, api-projects, db-schema, db-migrations, db-indexes]
      
      frontend:
        title: "Фронтенд"
        nodes: [ui-design-system, ui-forms, ui-tables, page-dashboard, page-tasks, page-settings]
      
      testing:
        title: "Тестирование"
        nodes: [e2e-tests, performance-tests]
      
      milestones:
        title: "Вехи"
        nodes: [release-v1]

  # ============================================================
  # Бэклог — задачи без расписания
  # ============================================================
  backlog:
    title: "Бэклог"
    where:
      has_schedule: false  # только незапланированные узлы
    order_by: effort       # сортировка по трудозатратам

  # ============================================================
  # Задачи в работе
  # ============================================================
  in-progress:
    title: "В работе"
    where:
      status: [in_progress, review]
    order_by: title

  # ============================================================
  # Задачи бэкенд-команды
  # ============================================================
  backend-tasks:
    title: "Задачи бэкенда"
    where:
      parent: backend  # все потомки узла backend
      kind: [task]
    order_by: status

  # ============================================================
  # Дерево проекта
  # ============================================================
  tree:
    title: "Структура проекта"
    # Без фильтров — показывает всё дерево

  # ============================================================
  # Граф зависимостей
  # ============================================================
  deps:
    title: "Зависимости"
    where:
      kind: [task]  # только задачи
